### PR TITLE
Add Minimum Torrents

### LINKED ISSUE #53: [Feat Request] Minimum Torrents
Can there be an option to have a minimum number of set torrents before any get removed.

### PR DESCRIPTION
**Pull request by kaiserbh**
Closes #53

### CODE REVIEW

**Comment by saltydk** [comment]
Why not just use disk space? What upside is there to using a number of torrents?

**Comment by kaiserbh** [comment]
> Why not just use disk space? What upside is there to using a number of torrents?

Not exactly sure but maybe @evoandroidevo can shed some light as they wanted the feature.

**Comment by saltydk** [comment]
Could be not knowing it is a thing I suppose since it is missing an example.
```yml
FreeSpaceGB() < 128
```
In case that covers his use case, if he looks here anyway.

**Comment by evoandroidevo** [comment]
i use it to get points on some trackers. why keep 100 if only need to keep 5

**Comment by saltydk** [comment]
> i use it to get points on some trackers

Doesn't really answer the question. Do you mean you wanted torrent number per tracker or?

**Comment by evoandroidevo** [comment]
> > i use it to get points on some trackers
> 
> Doesn't really answer the question. Do you mean you wanted torrent number per tracker or?

This works good enough for my use case. But having an option to set a min per label would be better.

**Comment by saltydk** [comment]
> > > i use it to get points on some trackers
> > 
> > 
> > Doesn't really answer the question. Do you mean you wanted torrent number per tracker or?
> 
> This works good enough for my use case. But having an option to set a min per label would be better.

Sure but that was probably useful to put in your issue as this implementation does neither.

**Comment by evoandroidevo** [comment]
this implementation is what i asked for originally.

**Comment by saltydk** [comment]
> this implementation is what i asked for originally.

Sure but it would only work for people using a single tracker in the case of points, although 5 torrents for that seems rather low.

Not sure what @l3uddz thinks about this but I would suggest implementing it on per category/label and/or tracker basis and then it might be more useful to others, personally I would just use the disk space feature.

**Pull request closed without merging**
